version: "3.3"
services:
  promethes:
    image: prom/prometheus:latest
    container_name: prometheus
    network_mode: host
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

volumes:
  prometheus_data: