{
 "title": "Passive Gateway Dash",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "process_cpu_usage * 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(jvm_memory_used_bytes{area=\"heap\"}) / sum(jvm_memory_max_bytes{area=\"heap\"})) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "/lastDayReport HTTP Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{uri=\"/lastDayReport\"}) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "/currentStatus HTTP Requests Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "(sum(http_server_requests_seconds_count{uri=\"/currentStatus\"}) by (status))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open Data Hub latest status request total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "open_data_hub_last_status_counter_total",
     "legendFormat": "Last Status"
    },
    {
     "expr": "open_data_hub_report_counter_total",
     "legendFormat": "Daily Report"
    }
   ]
  }
 ]
}